### ISSUE TITLE
firefox errors with "ReferenceError: getMessage is not defined"

### ISSUE THREAD

**Issue by kenese** [theblacksmith/chai-param#1]
Chai-param is erroring in chai-param.js on line:74, saying it can't see the named function getMessage, which is defined directly after that statement. It should work (and does in other browsers). 
Replacing that line with 
    utils.getMessage =  function getMessage (obj, args) {

fixes it. It seems firefox has a bug where it doesn't always hoist named functions
http://stackoverflow.com/questions/29812849/firefox-function-hoisting-error

**Comment by svallory** [comment]
v0.1.1 published to fix it :)

**Comment by kenese** [comment]
Nice! Thanks :)
